### PR TITLE
Minor updates/improvements

### PR DESCRIPTION
**Pull request by flaub**
* Target net451
* Use dotnet SDK (project.json) for simplified dependency management
* Add .xproj for IDE support
* Tweak MonoAssemblyResolver to work on any platform (including macOS).
* Resharper suggestions/improvements

### CODE REVIEW

**Comment by jbatonnet** [comment]
Hi @flaub,

Thank you for your work and your contribution.

I disagree with some aspect of your changes, let me explain :
- You translated to .NET Core tooling the project format. .NET Core tooling is not yet mature enough to be used in production. .NET teams are currently rolling back their changes to switch back to csproj versions. Beyond this philosophical choice, I work in a company using Visual Studio 2012, and I want them to be able to build this project, without them having to install more tooling. This does not prevent Visual Studio >= 2015 from playing well between csproj and xproj in the same solution.
- I saw you applied Resharper policy to use var instead of strongly typed types. I think this is a terrible choice for C# programming. Plain text types allow developers to quickly understand the type by just reading the variable declaration. I personally use var in the same spirit as auto in C++, when type is too complex to be relevant.

Except those two "style" changes, I totally agree with other modifications :
- Usage of .NET 4.5.1
- Mono library location

I was currently investigating a clean way to submit a Pull Request with these changes to Microsoft.
As the core of this modification is not very "clean", I should integrate those changes to MS libraries directly.

Julien Batonnet

**Comment by jbatonnet** [comment]
Moreover, it seems that I don't need this extension anymore on Mono 4 and ASP.NET Core 1.1.
I'm testing it..

**Comment by flaub** [comment]
That's reasonable. 

I found that I still needed this even for ASP.NET Core 1.1. I think the overall issue is that Mono is not a supported runtime for .NET Core. I've done quite a bit of research on this, here's what I was able to piece together:

https://github.com/flaub/aspnet-core-net462-mono

**Comment by jbatonnet** [comment]
Interesting, I came accross some of these issues while trying to build my own website to run on a Raspberry Pi. I wrote some explanations here : https://www.thedju.net/articles/asp-net-core-mono-linux

Unfortunately, I did encounter 2 blockers :
- The CPU of the Raspberry Pi 1 running Raspbian does not provide the required feature set to run Mono > v3 that is necessary to run ASP.NET Core assemblies
- I did not manage to get libuv working on my old RPi with Kestrel, even when rebuilding it and trying to debug it.

For the first part, I managed to find a way to build Mono 4 without hard floating point support. It does run considerably slower than normal, but at least it runs.
The second one was more tricky so I implemented a custom server support to replace Kestrel using EmbedIO : https://github.com/jbatonnet/Microsoft.AspNetCore.Server.EmbedIO

After some time, I did realize that EmbedIO does only use HttpListener from System.Net, so I built two other implementations : 
- With NHttp (on my BitBucket)
- With the basic HttpListener, to get rid of any NuGet dependency : https://github.com/jbatonnet/Microsoft.AspNetCore.Server.HttpListener (and i saw you did a similar thing just a few hours after me 😄)

Anyway : 
- This NuGet package should be enough to run things on RPi (and Mac ?) for now
- .NET Standard 2 will come soon (at least I hope so), and Mono/Xamarin should benefit as Microsoft is here
- If a fix is needed Microsoft-side, it's here (the same thing I manually patch with my hack) : 
    - https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/Resolution/DotNetReferenceAssembliesPathResolver.cs
    - https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/Resolution/ReferenceAssemblyPathResolver.cs

**Comment by flaub** [comment]
That's funny. I actually wrote the `SocketHttpListener` adapter a few months ago internally for my company. I was looking at EmbedIO and wondering how it would do. What's great about `SocketHttpListener` is that it works on Windows and Mono equally well since it's a pure C# impl. It's probably not great for performance but that wasn't a constraint for us. We wanted to not require the use of `HTTP.sys` on windows, which is why we didn't use `HttpListener` directly.

I'll have to look into your Mvc Precompilation solution. I've been meaning to handle this somehow.

**Comment by flaub** [comment]
I have my fingers crossed that Microsoft will fully support Mono in the near future so all of this can be obsoleted. In the meantime, I'm glad that .NET Core is open source so we even have a chance to make workarounds.

**Pull request closed without merging**
